feat(common): backend 작업중인 내용 머지
pseudolab/pseudolab-backend pull request #1
Opened 2024-02-21 13:51 UTC by 4roring

2024-02-21 13:53 UTC, ehddnr301 requested changes
완료되면 다시 확인 해보겠습니다 👍

2024-02-23 11:12 UTC, ehddnr301 approved these changes
💬 개발실 노션에 [유저 업적 시스템](https://www.notion.so/chanrankim/0792d3e4903c4bcf8de1e3e31a7d5876) 에 discord 정보를 크롤링한 데이터를 임시로 올려놓아 보았는데요!
discord 연동시에 해당 csv에 담긴것처럼 Bigint형태의 id값을 얻을 수 있다면 discord 업적도 연동하면 재미있을것 같습니다.

❓discord를 통한 인증은 구현이 된것으로 보이는데 맞을까요? 넘 고생많으셨습니다!

2024-02-25 05:23 UTC, SunandBean commented
> 💬 개발실 노션에 [유저 업적 시스템](https://www.notion.so/chanrankim/0792d3e4903c4bcf8de1e3e31a7d5876) 에 discord 정보를 크롤링한 데이터를 임시로 올려놓아 보았는데요! discord 연동시에 해당 csv에 담긴것처럼 Bigint형태의 id값을 얻을 수 있다면 discord 업적도 연동하면 재미있을것 같습니다.
> 
> ❓discord를 통한 인증은 구현이 된것으로 보이는데 맞을까요? 넘 고생많으셨습니다!

💬 유저 프로파일 페이지에 업적이 연동될 것 같으면 좋겠네요! 업적 부분은 나중에 웹페이지에서 알림 기능 구현할 필요가 있다면 같이 넣어봐도 좋을 것 같네요 ㅎㅎ

2024-02-25 05:35 UTC, SunandBean commented on README.md
> +Poetry Interpreter 통하여 poetry 환경 생성 및 지정
💊 README 파일 가독성 좋게 H1, H2, H3 형식 맞춰서 쓰면 좋을 것 같습니다~! 
❓ 운영체제별로 설치 방법도 같을까요?

```suggestion
## 시작하기

### poetry 설치

Root 경로에서 아래의 명령어 수행
- `poetry install`

pycharm을 사용한다면  
File - Settings - Project - Python Interpreter  
Add Interpreter - Add Local Interpreter  
Poetry Interpreter 통하여 poetry 환경 생성 및 지정
```

2024-02-25 05:35 UTC, SunandBean commented on app/api/auth/discord_login.py
> +async def discord_login(request_token: OAuth2SchemeDepends) -> RedirectResponse:
💊 argument, output의 타입 명시에 대한 규칙을 정하면 좋을 것 같습니다. 어디엔 명시하고 어디엔 명시하지 않고 있네요. 만약 타입을 명시하기로 정한다면 [Rust처럼 안전하게 Python 코드 작성하기](https://www.cv-learn.com/20230609-python-like-rust/)를 참고해서 정해보면 좋을 것 같습니다.

2024-02-25 05:35 UTC, SunandBean commented on pyproject.toml
💊 이용하는 모든 패키지의 버전은 고정해서 개발하는게 어떨까요? 개발 환경 동일하게 유지하기 위해서는 동일한 버전으로 관리하고, 버전업이 필요한 경우에 프로젝트 리딩해주시는 분이 버전업 테스트 해보시고 다 같이 일괄 업데이트 하는게 좋을 것 같아서요.

2024-02-25 05:37 UTC, 4roring commented on pyproject.toml
poetry에 버전 고정되어있습니다!

2024-02-25 07:23 UTC, merged